CREATE TABLE USER(
correo VARCHAR(255)  PRIMARY KEY NOT NULL,
nombre VARCHAR(255) NOT NULL,
apellido VARCHAR (255) NOT NULL,
clave VARCHAR(255) NOT NULL,
celular VARCHAR (255) NOT NULL,
direccion VARCHAR(255) NOT NULL,
ciudad VARCHAR (255) NOT NULL
);
CREATE TABLE ADMINISTRADOR(
correo VARCHAR(255)  PRIMARY KEY NOT NULL,
clave VARCHAR(255) NOT NULL
);
CREATE TABLE PRODUCTO(
codigo  VARCHAR(255)  PRIMARY KEY NOT NULL,
nombre VARCHAR(255)  NOT NULL,
precio varchar(255),
color VARCHAR(255)  NOT NULL,
cantidad VARCHAR(255),
imagen varchar(500) 

);